### ISSUE TITLE
Cannot select root

### ISSUE THREAD

**Issue by ChristopherChudzicki** [unconed/mathbox#18]
### Steps to reproduce
1. Open `examples/test/curve.html`
2. In dev console, `mathbox.select('root')`

### Expected
root node is returned

### Actual
Empty selection is returned

This is a regression that was introduced in https://gitgud.io/unconed/mathbox/-/merge_requests/25

**Comment by sritchie** [comment]
Ah! Very interesting. That feels related to the component reload bug… nice find here!

**Comment by ChristopherChudzicki** [comment]
I've decided this is actually not a bug. The old behavior in which `mathBox.select('root')` returned the root node was a bug.

I'm not going to try and dig up the exact CSS spec for this, but elements seem not to be selectable from themselves. For example:
```
html = document.querySelector('html') // returns HTML element
html.querySelector('html') // returns null
```

**Comment by sritchie** [comment]
Sounds correct to me.

**Comment by sritchie** [comment]
#57 adds a way around this, since we could now call `root(...)`  from any level.
