### ISSUE TITLE
Suggestion: scalar/complex fields

### ISSUE THREAD

**Issue by v-alisei** [unconed/mathbox#37]
Hi there! I found out about math3d recently and I appreciated the work of both of these projects! And I'm excited to contribute. The thing I want to add looks something like this.
https://harryhatchard.com/hydrogen/index.html
this guy made this using three.js fragment shaders. Initially I thought to make everything myself, and make a PR, but I found out that this is hard when you have no experience with shaders. So here I am.
@sritchie @unconed @ChristopherChudzicki 
As far as I know, mathbox allows to directly pass a shader to webGL. 
At first I want to know are you interested in doing this,
and if so, can you help me with either developing shaders, implementing a proper math3d>mathbox and mathbox>three.js interface?

**Comment by ChristopherChudzicki** [comment]
@v-alisei My chrome browser thinks that the link you posted is "Not secure", so I have not looked at it.

That said: Most of my free-time in software at the moment is devoted to re-writing Math3d in Typescript. Beyond adding better Typescript support and fixing bugs I encounter, I probably won't have much time to contribute to mathbox.

And, unfortunately, I am not much a GLSL expert, so I can't give much advice around shaders. I do believe that `mathbox` supports passing custom shaders, e.g., https://github.com/unconed/mathbox/blob/master/examples/test/shader.html.

**Comment by sritchie** [comment]
@v-alisei , closing this for now, but please feel free to open this again if you decide to work on it!
