### ISSUE TITLE
get(k) on mathbox root ignores bound properties

### ISSUE THREAD

**Issue by sritchie** [unconed/mathbox#59]
Add this to some example:

```js
mathbox.bind({
  focus: (time, delta) => {
    console.log(mathbox.get("focus"));
    5 * Math.sin(time * 0.5);
  },
});
```

And note that "1", the default, is printed many times instead of

- the function value
- the current value of "focus" for mathbox

**Comment by ChristopherChudzicki** [comment]
I think this does work as intended, but you need to `return` the focus value:
```
  focus: (time, delta) => {
    console.log(mathbox.get("focus"));
    return 5 * Math.sin(time * 0.5); //             <--- return here
  },
```

(Do negative focuses work?)

**Comment by sritchie** [comment]
Huh, I thought the arrow form returned its final expression? This example was in fact working for me and pulsing the scene, but the console was printing the same value. Does that change with return??

Answers incoming to your other questions plus some thoughts on threestrap, once I get a family-free block. Thanks for looking at these!

**Comment by ChristopherChudzicki** [comment]
Re arrow functions:
```ts
// this returns 5
const f = () => 5
// the braces open a scope, the scope does not have a value, so this returns `undefined`
const g = () => {
  5
}
// which is annoying if you want to return an object from an arrow function
// so the way to do that is with extra parens
const h = () => ({ value: 5 })
```

Not sure why you saw the scene pulsing. Was focus being set elsewhere? Or widths?

**Comment by sritchie** [comment]
Yes, you're right! I almost certainly just didn't refresh when adding the block and console.log statements.

**Comment by sritchie** [comment]
Thanks for the check here...
